--------------------------------------------------------
--  Fichier créé - mercredi-avril-07-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table GATEAUX
--------------------------------------------------------

  CREATE TABLE "GHADA"."GATEAUX" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"QUANTITY" NUMBER, 
	"PRICE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into GHADA.GATEAUX
SET DEFINE OFF;
Insert into GHADA.GATEAUX (ID,NAME,QUANTITY,PRICE) values ('1','ghjkl','5','33');
Insert into GHADA.GATEAUX (ID,NAME,QUANTITY,PRICE) values ('2','yyyyy','9','36');
Insert into GHADA.GATEAUX (ID,NAME,QUANTITY,PRICE) values ('3','Muffin','30','15');
Insert into GHADA.GATEAUX (ID,NAME,QUANTITY,PRICE) values ('4','test','20','51');
Insert into GHADA.GATEAUX (ID,NAME,QUANTITY,PRICE) values ('5','tesst','20','53');
--------------------------------------------------------
--  DDL for Index GATEAUX_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GHADA"."GATEAUX_PK" ON "GHADA"."GATEAUX" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index GATEAUX_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "GHADA"."GATEAUX_UK1" ON "GHADA"."GATEAUX" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table GATEAUX
--------------------------------------------------------

  ALTER TABLE "GHADA"."GATEAUX" ADD CONSTRAINT "GATEAUX_UK1" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GHADA"."GATEAUX" ADD CONSTRAINT "GATEAUX_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GHADA"."GATEAUX" MODIFY ("ID" NOT NULL ENABLE);
