--------------------------------------------------------
--  File created - Thursday-May-20-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CATEGORY
--------------------------------------------------------

  CREATE TABLE "IYED"."CATEGORY" 
   (	"ID" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "IYED"."CLIENT" 
   (	"NOM" VARCHAR2(40 BYTE), 
	"ADRESSE" VARCHAR2(50 BYTE), 
	"ID" NUMBER(*,0), 
	"PRENOM" VARCHAR2(40 BYTE), 
	"EMAIL" VARCHAR2(40 BYTE), 
	"TEL" VARCHAR2(20 BYTE), 
	"JOINDATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMMANDE
--------------------------------------------------------

  CREATE TABLE "IYED"."COMMANDE" 
   (	"ID" VARCHAR2(20 BYTE), 
	"GATEAUXNAME" VARCHAR2(20 BYTE), 
	"SOMME" NUMBER, 
	"QUANTC" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COUPONS
--------------------------------------------------------

  CREATE TABLE "IYED"."COUPONS" 
   (	"ID" NUMBER(*,0), 
	"USES" NUMBER(*,0), 
	"CONSTRAINTS" LONG, 
	"STARTDATE" TIMESTAMP (6), 
	"CODE" VARCHAR2(20 BYTE), 
	"ENDDATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FILEATTENTE
--------------------------------------------------------

  CREATE TABLE "IYED"."FILEATTENTE" 
   (	"ID" NUMBER, 
	"RECETTE" NUMBER, 
	"ETAT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GATEAUX
--------------------------------------------------------

  CREATE TABLE "IYED"."GATEAUX" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"QUANTITY" NUMBER, 
	"PRICE" NUMBER, 
	"TYPE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MATERIEL
--------------------------------------------------------

  CREATE TABLE "IYED"."MATERIEL" 
   (	"ID_MATERIEL" NUMBER(*,0), 
	"NB_MATERIEL" NUMBER(*,0), 
	"NOM_MATERIEL" VARCHAR2(20 BYTE), 
	"DATE_ENTR" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUIT
--------------------------------------------------------

  CREATE TABLE "IYED"."PRODUIT" 
   (	"ID_INGREDIANT" NUMBER, 
	"NOM_INGREDIENT" VARCHAR2(20 BYTE), 
	"DATE_EXP" VARCHAR2(20 BYTE), 
	"QUANTITE_INGREDIENT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RECETTES
--------------------------------------------------------

  CREATE TABLE "IYED"."RECETTES" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"DUREE" NUMBER, 
	"ETAPES" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ROLE
--------------------------------------------------------

  CREATE TABLE "IYED"."ROLE" 
   (	"CIN" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"ROLE" VARCHAR2(20 BYTE), 
	"EARNING" NUMBER, 
	"BONUS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into IYED.CATEGORY
SET DEFINE OFF;
Insert into IYED.CATEGORY (ID,TYPE) values ('1','Cake');
Insert into IYED.CATEGORY (ID,TYPE) values ('2','Croissant ');
Insert into IYED.CATEGORY (ID,TYPE) values ('3','pattee');
Insert into IYED.CATEGORY (ID,TYPE) values ('123','categ1');
REM INSERTING into IYED.CLIENT
SET DEFINE OFF;
Insert into IYED.CLIENT (NOM,ADRESSE,ID,PRENOM,EMAIL,TEL,JOINDATE) values ('Gojo','Unlimited Void',53,'Satoru','gojo@gmail.com','94696969',to_timestamp('07-APR-21 19.16.37.141000000','DD-MON-RR HH24.MI.SSXFF'));
Insert into IYED.CLIENT (NOM,ADRESSE,ID,PRENOM,EMAIL,TEL,JOINDATE) values ('hhhh','ghedhehe',24,'hehe','hrhrhe@gmail.fr','gegegege',to_timestamp('25-MAR-21 20.22.47.198000000','DD-MON-RR HH24.MI.SSXFF'));
Insert into IYED.CLIENT (NOM,ADRESSE,ID,PRENOM,EMAIL,TEL,JOINDATE) values ('iyed','05 rue',57,'bhd','jijoiioj@gmail.com','97104419',to_timestamp('08-APR-21 14.59.09.889000000','DD-MON-RR HH24.MI.SSXFF'));
Insert into IYED.CLIENT (NOM,ADRESSE,ID,PRENOM,EMAIL,TEL,JOINDATE) values ('jjjjjj','nnnnnn',61,'jjjjj','jjjjj@gmail.com','5455111',to_timestamp('27-APR-21 19.37.42.473000000','DD-MON-RR HH24.MI.SSXFF'));
Insert into IYED.CLIENT (NOM,ADRESSE,ID,PRENOM,EMAIL,TEL,JOINDATE) values ('gjioajgoia','fagaga',62,'vpgjipgajio','goajogoai@gmail.com','94338545',to_timestamp('29-APR-21 13.18.04.798000000','DD-MON-RR HH24.MI.SSXFF'));
Insert into IYED.CLIENT (NOM,ADRESSE,ID,PRENOM,EMAIL,TEL,JOINDATE) values ('aaaa','cccc',63,'bbbb','ddgqggq@goga.fr','fgqgqgqgqgq',to_timestamp('01-MAY-21 20.15.23.064000000','DD-MON-RR HH24.MI.SSXFF'));
Insert into IYED.CLIENT (NOM,ADRESSE,ID,PRENOM,EMAIL,TEL,JOINDATE) values ('iyedo','05 rue de cobalto',64,'ben hadjo dahmeno','iyedo@gmailo.como','9412121d',to_timestamp('05-MAY-21 23.04.10.179000000','DD-MON-RR HH24.MI.SSXFF'));
Insert into IYED.CLIENT (NOM,ADRESSE,ID,PRENOM,EMAIL,TEL,JOINDATE) values ('Gojo','Unlimited Void',56,'Satoru','gojo@gmail.com','94696969',to_timestamp('07-APR-21 19.16.58.794000000','DD-MON-RR HH24.MI.SSXFF'));
Insert into IYED.CLIENT (NOM,ADRESSE,ID,PRENOM,EMAIL,TEL,JOINDATE) values ('iyedoaaa','05 rue de cobalto',65,'ben hadjo dahmeno','iyedo@gmailo.como','9412121',to_timestamp('05-MAY-21 23.04.21.878000000','DD-MON-RR HH24.MI.SSXFF'));
Insert into IYED.CLIENT (NOM,ADRESSE,ID,PRENOM,EMAIL,TEL,JOINDATE) values ('jj','05555',66,'oijoij','iojdioqd@gmail.com','997878',to_timestamp('06-MAY-21 12.24.46.339000000','DD-MON-RR HH24.MI.SSXFF'));
Insert into IYED.CLIENT (NOM,ADRESSE,ID,PRENOM,EMAIL,TEL,JOINDATE) values ('jogiajgioa','fqjoiogqjoigq',67,'gajgiagj','aaaa@gmail.com','94338745',to_timestamp('06-MAY-21 13.50.24.865000000','DD-MON-RR HH24.MI.SSXFF'));
REM INSERTING into IYED.COMMANDE
SET DEFINE OFF;
Insert into IYED.COMMANDE (ID,GATEAUXNAME,SOMME,QUANTC) values ('2','yyyyy',22,null);
Insert into IYED.COMMANDE (ID,GATEAUXNAME,SOMME,QUANTC) values ('5','yyyyy',324,9);
Insert into IYED.COMMANDE (ID,GATEAUXNAME,SOMME,QUANTC) values ('6','ghjkl',33,1);
REM INSERTING into IYED.COUPONS
SET DEFINE OFF;
Insert into IYED.COUPONS (ID,USES,CONSTRAINTS,STARTDATE,CODE,ENDDATE) values (28,55555,'{}',to_timestamp('06-APR-21 00.00.00.000000000','DD-MON-RR HH24.MI.SSXFF'),'couajogifag',to_timestamp('07-APR-21 00.00.00.000000000','DD-MON-RR HH24.MI.SSXFF'));
Insert into IYED.COUPONS (ID,USES,CONSTRAINTS,STARTDATE,CODE,ENDDATE) values (29,55555,'{}',to_timestamp('06-APR-21 00.00.00.000000000','DD-MON-RR HH24.MI.SSXFF'),'couajogifag',to_timestamp('07-APR-21 00.00.00.000000000','DD-MON-RR HH24.MI.SSXFF'));
Insert into IYED.COUPONS (ID,USES,CONSTRAINTS,STARTDATE,CODE,ENDDATE) values (30,55555,'{}',to_timestamp('06-APR-21 00.00.00.000000000','DD-MON-RR HH24.MI.SSXFF'),'couajogifag',to_timestamp('07-APR-21 00.00.00.000000000','DD-MON-RR HH24.MI.SSXFF'));
Insert into IYED.COUPONS (ID,USES,CONSTRAINTS,STARTDATE,CODE,ENDDATE) values (21,123,'{}',to_timestamp('07-APR-21 00.00.00.000000000','DD-MON-RR HH24.MI.SSXFF'),'iyedbhd',to_timestamp('23-APR-21 00.00.00.000000000','DD-MON-RR HH24.MI.SSXFF'));
Insert into IYED.COUPONS (ID,USES,CONSTRAINTS,STARTDATE,CODE,ENDDATE) values (31,55555,'{}',to_timestamp('06-APR-21 00.00.00.000000000','DD-MON-RR HH24.MI.SSXFF'),'couajogifag',to_timestamp('07-APR-21 00.00.00.000000000','DD-MON-RR HH24.MI.SSXFF'));
Insert into IYED.COUPONS (ID,USES,CONSTRAINTS,STARTDATE,CODE,ENDDATE) values (32,123,'{}',to_timestamp('08-APR-21 00.00.00.000000000','DD-MON-RR HH24.MI.SSXFF'),'nice',to_timestamp('08-APR-21 00.00.00.000000000','DD-MON-RR HH24.MI.SSXFF'));
Insert into IYED.COUPONS (ID,USES,CONSTRAINTS,STARTDATE,CODE,ENDDATE) values (44,105,'{}',to_timestamp('06-MAY-21 00.00.00.000000000','DD-MON-RR HH24.MI.SSXFF'),'fqgqg',to_timestamp('06-MAY-21 00.00.00.000000000','DD-MON-RR HH24.MI.SSXFF'));
Insert into IYED.COUPONS (ID,USES,CONSTRAINTS,STARTDATE,CODE,ENDDATE) values (23,48888,'{"totalSup": 1234}',to_timestamp('05-APR-21 00.00.00.000000000','DD-MON-RR HH24.MI.SSXFF'),'ayeeeeee123',to_timestamp('12-APR-21 00.00.00.000000000','DD-MON-RR HH24.MI.SSXFF'));
Insert into IYED.COUPONS (ID,USES,CONSTRAINTS,STARTDATE,CODE,ENDDATE) values (24,48888,'{}',to_timestamp('05-APR-21 00.00.00.000000000','DD-MON-RR HH24.MI.SSXFF'),'ayeeeeee123',to_timestamp('12-APR-21 00.00.00.000000000','DD-MON-RR HH24.MI.SSXFF'));
Insert into IYED.COUPONS (ID,USES,CONSTRAINTS,STARTDATE,CODE,ENDDATE) values (25,1522,'{"totalSup": 2222}',to_timestamp('13-APR-21 00.00.00.000000000','DD-MON-RR HH24.MI.SSXFF'),'okokoko',to_timestamp('07-APR-21 00.00.00.000000000','DD-MON-RR HH24.MI.SSXFF'));
Insert into IYED.COUPONS (ID,USES,CONSTRAINTS,STARTDATE,CODE,ENDDATE) values (26,1522,'{"totalSup": 2222}',to_timestamp('13-APR-21 00.00.00.000000000','DD-MON-RR HH24.MI.SSXFF'),'okokoko',to_timestamp('07-APR-21 00.00.00.000000000','DD-MON-RR HH24.MI.SSXFF'));
Insert into IYED.COUPONS (ID,USES,CONSTRAINTS,STARTDATE,CODE,ENDDATE) values (27,1522,'{"totalSup": 2222}',to_timestamp('13-APR-21 00.00.00.000000000','DD-MON-RR HH24.MI.SSXFF'),'okokoko',to_timestamp('07-APR-21 00.00.00.000000000','DD-MON-RR HH24.MI.SSXFF'));
Insert into IYED.COUPONS (ID,USES,CONSTRAINTS,STARTDATE,CODE,ENDDATE) values (33,100,'{}',to_timestamp('08-APR-21 00.00.00.000000000','DD-MON-RR HH24.MI.SSXFF'),'5456456',to_timestamp('08-APR-21 00.00.00.000000000','DD-MON-RR HH24.MI.SSXFF'));
Insert into IYED.COUPONS (ID,USES,CONSTRAINTS,STARTDATE,CODE,ENDDATE) values (34,555,'{}',to_timestamp('14-APR-21 00.00.00.000000000','DD-MON-RR HH24.MI.SSXFF'),'jojoioji',to_timestamp('08-APR-21 00.00.00.000000000','DD-MON-RR HH24.MI.SSXFF'));
Insert into IYED.COUPONS (ID,USES,CONSTRAINTS,STARTDATE,CODE,ENDDATE) values (35,123,'{}',to_timestamp('08-APR-21 00.00.00.000000000','DD-MON-RR HH24.MI.SSXFF'),'okioki',to_timestamp('08-APR-21 00.00.00.000000000','DD-MON-RR HH24.MI.SSXFF'));
Insert into IYED.COUPONS (ID,USES,CONSTRAINTS,STARTDATE,CODE,ENDDATE) values (36,123,'{}',to_timestamp('08-APR-21 00.00.00.000000000','DD-MON-RR HH24.MI.SSXFF'),'okiiiiiii',to_timestamp('08-APR-21 00.00.00.000000000','DD-MON-RR HH24.MI.SSXFF'));
Insert into IYED.COUPONS (ID,USES,CONSTRAINTS,STARTDATE,CODE,ENDDATE) values (37,123,'{}',to_timestamp('08-APR-21 00.00.00.000000000','DD-MON-RR HH24.MI.SSXFF'),'okiiiiiii',to_timestamp('08-APR-21 00.00.00.000000000','DD-MON-RR HH24.MI.SSXFF'));
Insert into IYED.COUPONS (ID,USES,CONSTRAINTS,STARTDATE,CODE,ENDDATE) values (38,123,'{}',to_timestamp('08-APR-21 00.00.00.000000000','DD-MON-RR HH24.MI.SSXFF'),'testing email yay',to_timestamp('08-APR-21 00.00.00.000000000','DD-MON-RR HH24.MI.SSXFF'));
Insert into IYED.COUPONS (ID,USES,CONSTRAINTS,STARTDATE,CODE,ENDDATE) values (42,1000,'{}',to_timestamp('05-MAY-21 00.00.00.000000000','DD-MON-RR HH24.MI.SSXFF'),'ooooo',to_timestamp('05-MAY-21 00.00.00.000000000','DD-MON-RR HH24.MI.SSXFF'));
Insert into IYED.COUPONS (ID,USES,CONSTRAINTS,STARTDATE,CODE,ENDDATE) values (40,500,'{}',to_timestamp('22-APR-21 00.00.00.000000000','DD-MON-RR HH24.MI.SSXFF'),'test',to_timestamp('22-APR-21 00.00.00.000000000','DD-MON-RR HH24.MI.SSXFF'));
Insert into IYED.COUPONS (ID,USES,CONSTRAINTS,STARTDATE,CODE,ENDDATE) values (41,5555,'{}',to_timestamp('03-MAY-21 00.00.00.000000000','DD-MON-RR HH24.MI.SSXFF'),'iii',to_timestamp('03-MAY-21 00.00.00.000000000','DD-MON-RR HH24.MI.SSXFF'));
Insert into IYED.COUPONS (ID,USES,CONSTRAINTS,STARTDATE,CODE,ENDDATE) values (43,11111,'{}',to_timestamp('06-MAY-21 00.00.00.000000000','DD-MON-RR HH24.MI.SSXFF'),'12133',to_timestamp('06-MAY-21 00.00.00.000000000','DD-MON-RR HH24.MI.SSXFF'));
REM INSERTING into IYED.FILEATTENTE
SET DEFINE OFF;
Insert into IYED.FILEATTENTE (ID,RECETTE,ETAT) values (0,null,null);
REM INSERTING into IYED.GATEAUX
SET DEFINE OFF;
Insert into IYED.GATEAUX (ID,NAME,QUANTITY,PRICE,TYPE) values ('17','chey7a',19,700,'Croissant ');
Insert into IYED.GATEAUX (ID,NAME,QUANTITY,PRICE,TYPE) values ('16','bel ton',9,1000,'pattee');
Insert into IYED.GATEAUX (ID,NAME,QUANTITY,PRICE,TYPE) values ('20','ayyy esssm',20,20,'Cake');
REM INSERTING into IYED.MATERIEL
SET DEFINE OFF;
Insert into IYED.MATERIEL (ID_MATERIEL,NB_MATERIEL,NOM_MATERIEL,DATE_ENTR) values (11,12,'bat','20/01/2000');
REM INSERTING into IYED.PRODUIT
SET DEFINE OFF;
Insert into IYED.PRODUIT (ID_INGREDIANT,NOM_INGREDIENT,DATE_EXP,QUANTITE_INGREDIENT) values (2,'chocolat','22/01/2000',7);
Insert into IYED.PRODUIT (ID_INGREDIANT,NOM_INGREDIENT,DATE_EXP,QUANTITE_INGREDIENT) values (3,'farine','28/01/1222',7);
Insert into IYED.PRODUIT (ID_INGREDIANT,NOM_INGREDIENT,DATE_EXP,QUANTITE_INGREDIENT) values (1,'sucre','11/01/2000',4);
REM INSERTING into IYED.RECETTES
SET DEFINE OFF;
Insert into IYED.RECETTES (ID,NOM,DUREE,ETAPES) values (5,'gateau chocolat',120,null);
Insert into IYED.RECETTES (ID,NOM,DUREE,ETAPES) values (2,'Crepe chocolat',660,null);
Insert into IYED.RECETTES (ID,NOM,DUREE,ETAPES) values (6,'Muffins',500,null);
Insert into IYED.RECETTES (ID,NOM,DUREE,ETAPES) values (9,'Pizza',1000,null);
Insert into IYED.RECETTES (ID,NOM,DUREE,ETAPES) values (10,'Test',600,null);
REM INSERTING into IYED.ROLE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index CATEGORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IYED"."CATEGORY_PK" ON "IYED"."CATEGORY" ("TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CLIENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IYED"."CLIENT_PK" ON "IYED"."CLIENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COMMANDE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IYED"."COMMANDE_PK" ON "IYED"."COMMANDE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COUPONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IYED"."COUPONS_PK" ON "IYED"."COUPONS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FILEATTENTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IYED"."FILEATTENTE_PK" ON "IYED"."FILEATTENTE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index GATEAUX_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IYED"."GATEAUX_PK" ON "IYED"."GATEAUX" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index GATEAUX_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "IYED"."GATEAUX_UK1" ON "IYED"."GATEAUX" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RECETTES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IYED"."RECETTES_PK" ON "IYED"."RECETTES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger CLIENT_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "IYED"."CLIENT_TRG" 
BEFORE INSERT ON CLIENT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "IYED"."CLIENT_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CLIENT_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "IYED"."CLIENT_TRG1" 
BEFORE INSERT ON CLIENT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT CLIENT_SEQ1.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "IYED"."CLIENT_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger COUPONS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "IYED"."COUPONS_TRG" 
BEFORE INSERT ON COUPONS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT COUPONS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "IYED"."COUPONS_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table CATEGORY
--------------------------------------------------------

  ALTER TABLE "IYED"."CATEGORY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "IYED"."CATEGORY" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "IYED"."CATEGORY" ADD CONSTRAINT "CATEGORY_PK" PRIMARY KEY ("TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "IYED"."CLIENT" MODIFY ("TEL" NOT NULL ENABLE);
  ALTER TABLE "IYED"."CLIENT" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "IYED"."CLIENT" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "IYED"."CLIENT" ADD CONSTRAINT "CLIENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IYED"."CLIENT" MODIFY ("ADRESSE" NOT NULL ENABLE);
  ALTER TABLE "IYED"."CLIENT" MODIFY ("NOM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMMANDE
--------------------------------------------------------

  ALTER TABLE "IYED"."COMMANDE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "IYED"."COMMANDE" ADD CONSTRAINT "COMMANDE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COUPONS
--------------------------------------------------------

  ALTER TABLE "IYED"."COUPONS" ADD CONSTRAINT "COUPONS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IYED"."COUPONS" MODIFY ("ENDDATE" NOT NULL ENABLE);
  ALTER TABLE "IYED"."COUPONS" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "IYED"."COUPONS" MODIFY ("STARTDATE" NOT NULL ENABLE);
  ALTER TABLE "IYED"."COUPONS" MODIFY ("CONSTRAINTS" NOT NULL ENABLE);
  ALTER TABLE "IYED"."COUPONS" MODIFY ("USES" NOT NULL ENABLE);
  ALTER TABLE "IYED"."COUPONS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FILEATTENTE
--------------------------------------------------------

  ALTER TABLE "IYED"."FILEATTENTE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "IYED"."FILEATTENTE" ADD CONSTRAINT "FILEATTENTE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GATEAUX
--------------------------------------------------------

  ALTER TABLE "IYED"."GATEAUX" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "IYED"."GATEAUX" ADD CONSTRAINT "GATEAUX_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IYED"."GATEAUX" ADD CONSTRAINT "GATEAUX_UK1" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUIT
--------------------------------------------------------

  ALTER TABLE "IYED"."PRODUIT" MODIFY ("NOM_INGREDIENT" NOT NULL ENABLE);
  ALTER TABLE "IYED"."PRODUIT" MODIFY ("DATE_EXP" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RECETTES
--------------------------------------------------------

  ALTER TABLE "IYED"."RECETTES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "IYED"."RECETTES" ADD CONSTRAINT "RECETTES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GATEAUX
--------------------------------------------------------

  ALTER TABLE "IYED"."GATEAUX" ADD CONSTRAINT "GATEAUX_FK1" FOREIGN KEY ("TYPE")
	  REFERENCES "IYED"."CATEGORY" ("TYPE") ON DELETE CASCADE ENABLE;
